ccle_datasets: '/raid/vulcanspot_datasets/data/ccle' # Where to look for raw CCLE files


# RULES MARKED AS PANDAS SC are single threaded by nature, so there is no point
# in adding more cores, they won't go faster. Mem_mb is NOT a hard RAM limit,
# but an stimation of  max memory consumption (and thus, memory to allocate) 
# to be fed to the cluster query manager when executing the pipeline on cluster 
# environemtns. 

rules:
    default:
        res:
            threads: 1
            mem_mb:  4096 